eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19000/eureka/
#端口的使用请参考端口设计文档
server:
  port: 19099
spring:
  application:
    name: lotion-web-zuul
#启动所有映射(默认只有../actuator/health和../actuator/info)
management:
  endpoints:
    web:
      exposure:
        include: '*'
#zuul
zuul:
  routes:
    #指定web服务路由
    #zuul不需要指定顺序，DiscoveryClientRouteLocator会动态覆盖路由
    index:
      sensitiveHeaders:
      path: /index/**
      service-id: lotion-web-index
    webuis:
      sensitiveHeaders:
      path: /webuis/**
      service-id: lotion-web-webuis
    supervision:
      sensitiveHeaders:
      path: /supervision/**
      service-id: lotion-web-supervision
    control:
      sensitiveHeaders:
      path: /control/**
      service-id: lotion-web-control
    log:
      sensitiveHeaders:
      path: /log/**
      service-id: lotion-web-log
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId:  lotion-authcenter
  #不暴露未路由的服务，默认注册在eureka的服务路由为../${service-id}/
  ignored-services: '*'
  #设置全局参数为空覆盖默认过滤头信息，包括Cookie、Set-Cookie、Authorization
  sensitive-headers: Cookie,Set-Cookie,Authorization
  #不忽略安全请求头属性
  ignore-security-headers: false
  #解决加入Spring Security后的重定向问题，该问题会暴露具体Web服务的地址，该参数会在路由转发前为请求设置Host头信息，标识zuul网关地址
  add-host-header: true
  #忽略/**/actuator/**的请求
  ignored-patterns: /**/actuator/**,/lotion/**
#默认hystrix请求超时时间60秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#默认ribbon请求连接超时时间2秒
ribbon.ConnectTimeout: 2000
#默认ribbon请求读取超时时间20秒
ribbon.ReadTimeout: 20000
#默认ribbon请求可以重试
ribbon.OktoRetryOnAllOperations: true
#默认ribbon请求对当前实例重试次数为1
ribbon.MaxAutoRetries: 1
#默认ribbon请求切换实例重试次数为1
ribbon.MaxAutoRetriesNextServer: 1