eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19000/eureka/
#端口的使用请参考端口设计文档
server:
  port: 19099
spring:
  application:
    name: lotion-web-zuul
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
#启动所有映射(默认只有../actuator/health和../actuator/info)
management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:19033/oauth/token
      userAuthorizationUri: http://localhost:19033/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
#zuul
zuul:
  routes:
    #指定web服务路由
    #zuul不需要指定顺序，DiscoveryClientRouteLocator会动态覆盖路由
    index:
      sensitiveHeaders: "*"
      path: /index/**
      service-id: lotion-web-index
      strip-prefix: true
      custom-sensitive-headers: true
    webuis:
      sensitiveHeaders: A
      path: /webuis/**
      service-id: lotion-web-webuis
      strip-prefix: true
      custom-sensitive-headers: true
    supervision:
      sensitiveHeaders: "*"
      path: /supervision/**
      service-id: lotion-web-supervision
      strip-prefix: true
      custom-sensitive-headers: true
    control:
      sensitiveHeaders: "*"
      path: /control/**
      service-id: lotion-web-control
      strip-prefix: true
      custom-sensitive-headers: true
    log:
      sensitiveHeaders: "*"
      path: /log/**
      service-id: lotion-web-log
      strip-prefix: true
      custom-sensitive-headers: true
    mysql:
      sensitiveHeaders: "*"
      path: /mysql/**
      service-id: lotion-mysql-dao
      strip-prefix: true
      custom-sensitive-headers: true
    mongo:
      sensitiveHeaders: "*"
      path: /mongo/**
      service-id: lotion-mongo-dao
      strip-prefix: true
      custom-sensitive-headers: true
    redis:
      sensitiveHeaders: "*"
      path: /redis/**
      service-id: lotion-redis-dao
      strip-prefix: true
      custom-sensitive-headers: true
    #lotion-web-index: /index/**
    #lotion-web-webuis: /webuis/**
    #lotion-web-supervision: /supervision/**
    #lotion-web-control: /control/**
    #lotion-web-log: /log/**
  #不暴露未路由的服务，默认注册在eureka的服务路由为../${service-id}/
  ignored-services: '*'
  #设置全局参数为空覆盖默认过滤头信息，包括Cookie、Set-Cookie、Authorization
  sensitive-headers:
  #不忽略安全请求头属性
  ignore-security-headers: false
  #解决加入Spring Security后的重定向问题，该问题会暴露具体Web服务的地址，该参数会在路由转发前为请求设置Host头信息，标识zuul网关地址
  add-host-header: true
  #忽略/**/actuator/**的请求
  ignored-patterns: /**/actuator/**,/lotion/**
#默认hystrix请求超时时间60秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#默认ribbon请求连接超时时间2秒
ribbon.ConnectTimeout: 2000
#默认ribbon请求读取超时时间20秒
ribbon.ReadTimeout: 20000
#默认ribbon请求可以重试
ribbon.OktoRetryOnAllOperations: true
#默认ribbon请求对当前实例重试次数为1
ribbon.MaxAutoRetries: 1
#默认ribbon请求切换实例重试次数为1
ribbon.MaxAutoRetriesNextServer: 1
