server:
  port: 9080
spring:
  redis:
    database: 6   # Redis数据库索引（默认为0）
    host: localhost  # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:    # Redis服务器连接密码（默认为空）
    timeout: 0  # 连接超时时间（毫秒）
  redis2:
      database: 6   # Redis数据库索引（默认为0）
      host: 192.168.0.168  # Redis服务器地址
      port: 6379  # Redis服务器连接端口
      password:    # Redis服务器连接密码（默认为空）
      timeout: 0  # 连接超时时间（毫秒）
